{{- if .Values.networkPolicy.enabled }}
---
kind: NetworkPolicy
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: deny-from-other-namespaces
  labels: {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: producer-allow-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: producer
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: producer
      {{- include "cardano.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: relay
          {{- include "cardano.selectorLabels" . | nindent 10 }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace | quote }}
---
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: producer-deny-external-egress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: producer
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: producer
      {{- include "cardano.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - namespaceSelector: {}
---
kind: NetworkPolicy
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: relay-allow-external
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: relay
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: relay
      {{- include "cardano.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: 3001
---
kind: NetworkPolicy
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: allow-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "cardano.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: 12789
{{- end }}
---
kind: NetworkPolicy
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: air-gapped  # nothing in, nothing out
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  policyTypes:
  - Egress
  - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: admin
  ingress: []
  egress: []
