{{- if .Values.p2p.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cardano.fullname" . }}-p2p-nginx
  labels:
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.p2p.service.annotations }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: p2p
  selector:
    app.kubernetes.io/component: relay
    {{- include "cardano.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cardano.fullname" . }}-p2p
  labels:
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.p2p.service.annotations }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.p2p.service.type }}
  ports:
    - port: {{ .Values.p2p.service.port }}
      targetPort: 8080
      protocol: TCP
      name: p2p
  selector:
    app.kubernetes.io/component: p2p
    {{- include "cardano.selectorLabels" . | nindent 4 }}
{{- end }}
