{{- if .Values.p2p.clioEnabled }}
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ .Release.Name }}-topology-updater-push
  labels:
    app.kubernetes.io/component: updater
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_28="NET_RAW"
    checkov.io/skip2: CKV_K8S_37="admission of containers with capabilities."
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ .Release.Name }}-topology-updater-push
          labels:
            app.kubernetes.io/component: updater
            {{- include "cardano.selectorLabels" . | nindent 12 }}
        spec:
          automountServiceAccountToken: false
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: OnFailure
          initContainers:
            {{ include "cardano.readiness.waitForEkg" . | nindent 10 }}
          containers:
          - name: push
            securityContext:
              readOnlyRootFilesystem: true
            image: "{{- .Values.p2p.repository -}}:{{- .Values.p2p.tag | default .Chart.AppVersion -}}"
            imagePullPolicy: {{ .Values.p2p.pullPolicy }}
            resources:
              limits:
                cpu: "100m"
                memory: "64Mi"
            args:
            - --config
            - /p2p.yaml
            - push
            - --network
            {{- if eq .Values.environment.name "testnet" }}
            - "1097911063"
            {{- end }}
            {{- if eq .Values.environment.name "mainnet" }}
            - "764824073"
            {{- end }}
            - --port
            - {{ .Values.service.port | quote }}
            volumeMounts:
            - name: config
              mountPath: /p2p.yaml
              subPath: p2p.yaml
              readOnly: true
          volumes:
          - name: config
            configMap:
              name: {{ template "cardano.configName" . }}-p2p
{{- end }}
