{{- $fullName := include "cardano.fullname" . }}
{{- $wsHost := printf "%s-ogmios.%s" $fullName .Release.Namespace }}
---
{{- if not .Values.p2p.debug }}
debug: false
{{- else }}
debug: true
{{- end }}
server:
  listen-addr: ":8080"
  read-timeout: "1s"
{{- if eq .Values.environment.name "testnet" }}
  magic: 1097911063
  default-peer: "relays-new.cardano-testnet.iohkdev.io:3001"
{{- end }}
{{- if eq .Values.environment.name "mainnet" }}
  magic: 764824073
  default-peer: "relays-new.cardano-mainnet.iohk.io:3001"
{{- end }}
  max-peers: {{ .Values.p2p.maxPeers }}
client:
  ### how often to connect to ogmios websocket and fetch pool parameters.
  enabled: true
  period-seconds: "14400s" # controls how often the process will be repeated.
  fetch-max: 8000  # size of the go channel reading pool parameters at each iteration.
  endpoint: "ws://{{- $wsHost -}}:{{ .Values.ogmios.service.port }}"
  probe-timeout: "{{ .Values.p2p.probeTimeout }}"  # tcp probe timeout, a pool relay will be discarded if it does not answer (host down) to the tcp probe.
