# Requires a valid GITHUB_TOKEN
# --build-arg GITHUB_TOKEN=xxxx

# Runs goreleaser in Boring Crypto Go container in order to allow
# goreleaser to build a valid Boring Crypto binary

FROM goboring/golang:1.15.6b5

ARG GITHUB_TOKEN
ARG VERSION

RUN curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

WORKDIR /app
ADD . .

RUN go mod download
RUN GITHUB_TOKEN=$GITHUB_TOKEN GORELEASER_CURRENT_TAG=$VERSION goreleaser release --rm-dist --skip-validate
