on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: charts/cardano 
          quiet: true
          soft_fail: true # optional: do not return an error code if there are failed checks
          config_file: charts/cardano/.checkov
          baseline: charts/cardano/.checkov.baseline
          output_format: github_failed_only
