name: Checkov

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
#          api-key: ${{ secrets.BC_API_KEY }}
          directory: charts/cardano 
          quiet: true
          soft_fail: false # return an error code if there are failed checks not present in baseline
          config_file: charts/cardano/.checkov
          baseline: charts/cardano/.checkov.baseline

